# Generated by Django 3.1.7 on 2021-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsec', '0002_cve_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='data_mode',
            field=models.CharField(blank=True, choices=[('', '------------'), ('application', 'Requirements File'), ('services', 'KB LIST File')], default='no', max_length=100),
        ),
    ]
