# Generated by Django 3.1.7 on 2021-12-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsec', '0003_auto_20211209_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='organization',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='library',
            name='data_mode',
            field=models.CharField(blank=True, choices=[('', '------------'), ('application', 'Requirements File')], default='no', max_length=100),
        ),
    ]
